name: absenonline
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  flutter_animated_button: ^2.0.3
  google_sign_in: ^6.1.6
  pinput: ^4.0.0
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.1
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  google_nav_bar: ^5.0.6
  uuid: ^4.2.2
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.5
  data_table_2: ^2.5.15
# <<<<<<< Updated upstream
  flutter_barcode_scanner: ^2.0.0
# =======
  day_night_time_picker: ^1.3.1
  qr_code_scanner: ^1.0.1
  flutter_web_qrcode_scanner: ^1.1.1
# >>>>>>> Stashed changes

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - public/

