// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVvu7GRVh64ibZQZ437yrP2tew_FOZEjs',
    appId: '1:787455740387:web:8ebf3f2abeb89e243278d6',
    messagingSenderId: '787455740387',
    projectId: 'absenonline-dbbb9',
    authDomain: 'absenonline-dbbb9.firebaseapp.com',
    storageBucket: 'absenonline-dbbb9.appspot.com',
    measurementId: 'G-GVBT3YESL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbFpFAb2JGSo2dsrmKxpzQJ9YWBgLQZr8',
    appId: '1:787455740387:android:f820b652fe5909233278d6',
    messagingSenderId: '787455740387',
    projectId: 'absenonline-dbbb9',
    storageBucket: 'absenonline-dbbb9.appspot.com',
  );
}
